config/routes.rb
Rails.application.routes.draw do

  root to: 'categories#index'

  resources :categories, only: [:index] do
    resources :articles
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :body, presence: true

  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @category = Category.find_by(id: params[:category_id])
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    category = Category.find(params[:category_id])

    @article.category = category
    @article.save

    redirect_to category_articles_url(category)
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to category_article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to category_articles_url
  end

private
  def article_params
    params.require(:article).permit(:title, :body)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @categories = Category.find_by(id: params[:catagory_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for :article, url: category_article_path(@article), method: :patch do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', category_articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @category.articles.each do |article| %>
    <li><%= link_to article.title, category_article_path(@category, article) %></li>
    <%= link_to 'Edit', edit_category_article_path(@category, article) %>
    <%= link_to 'Delete', category_article_url(@category, article), method: :delete %>
  <% end %>
</ul>

<%= link_to "create new article", new_category_article_path(@category)%>

app/views/articles/new.html.erb
<h1>New Article</h1>
 <%= form_for :article, url: category_articles_path do |f| %>
   <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<div>
  <p>Title: <%= @article.title %></p>
  <p>Description: <%= @article.body %></p><br><br>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.title, category_articles_path(category) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craigslistjr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>